---
- hosts: brokers
  user: root
  vars:
    # paths for executables we don't have ansible modules for
    firewall_cmd: /usr/bin/firewall-cmd
    setsebool: /usr/sbin/setsebool
    gem: /usr/bin/gem 

    # config vars
    named_forwarder_ip: 4.2.2.2
    mq_provider: activemq
    mq_server_user: mcollective
    mq_server_password: marionette
    mongo_auth_user: openshift
    mongo_db_name: openshift_broker_dev
    mongo_auth_password: mooo

  tasks:
    
    ### Step 0 - SELinux Enforcing 
    - name: SELinux Enforcing (Targeted)
      selinux: policy=targeted state=enforcing
    - name: Ensure Installed - policycoreutils
      action: yum pkg=policycoreutils state=installed
    - name: SELinux - configure sebooleans
      command:  $setsebool -P httpd_unified=on 
                httpd_can_network_connect=on httpd_can_network_relay=on 
                httpd_run_stickshift=on named_write_master_zones=on 
                allow_ypbind=on
      

    ### FirewallD install/config
    - name: Ensure Install - firewalld
      action: yum pkg=firewalld state=installed
    #FIXME - There are certain states in which this will lock us out of the 
    #        system. Should template out all the configs to clean this up.
    - name: Start and Enable firewalld daemon 
      service: name=firewalld state=started enabled=yes
    # We can assume this is already set as an active service
    - name: FirewallD - permanent add-serivce sshd
      command: $firewall_cmd --permanent --add-service=ssh
      

    ### Setup Origin repos
    - name: Enable OpenShift Origin Nightly yum repo
      template: src=templates/openshift-origin-nightly.repo.j2
              dest=/etc/yum.repos.d/openshift-origin-nightly.repo
    - name: Enable OpenShift Origin Supplemental yum repo
      template: src=templates/openshift-origin-supplemental.repo.j2
                dest=/etc/yum.repos.d/openshift-origin-supplemental.repo

    ### Prereqs
    # NTP - sync first, then enable service
    - name: Ensure Install - ntpdate 
      action: yum pkg=ntpdate state=installed
    - name: Ensure Install - ntp 
      action: yum pkg=ntp state=installed
    - name: Stop ntp daemon for ntpdate sync
      service: name=ntpd state=stopped
    - name: Synchronize Clock with ntpdate
      action: command /usr/sbin/ntpdate 0.fedora.pool.ntp.org
    - name: Start and Enable ntp daemon 
      service: name=ntpd state=started enabled=yes

    # Install and configure ActiveMQ
    - name: Install ActiveMQ
      action: yum pkg=activemq state=latest
    - name: Configure ActiveMQ jetty.xml
      template: src=templates/activemq/jetty.xml.j2
                dest=/etc/activemq/jetty.xml
    - name: Configure ActiveMQ activemq.xml
      template: src=templates/activemq/activemq.xml.j2
                dest=/etc/activemq/activemq.xml
    - name: Configure ActiveMQ jetty-realm.properties
      template: src=templates/activemq/jetty-realm.properties.j2
                dest=/etc/activemq/jetty-realm.properties.xml
    - name: Configure ActiveMQ tmp-activemq.conf
      template: src=templates/activemq/tmp-activemq.conf.j2
                dest=/etc/tmpfiles.d/activemq.conf
    #FIXME - Can't seem to find good docs on what ports need 
    #        to be opened. Pinning this for later.
    #- name: FirewallD - permanent - add-port ActiveMQ
    #  command: $firewall_cmd --permanent --add-port=XXXX
    #- name: FirewallD - add-port ActiveMQ
    #  command: $firewall_cmd --add-port=XXXX

    # Install and configure BIND
    - name: Install bind
      action: yum pkg=bind state=latest
    - name: Install bind-utils
      action: yum pkg=bind-utils state=latest
    - name: Configure named dynamic_domain.db
      template: src=templates/named/dynamic-zone.db.j2
                dest=/var/named/dynamic/$ansible_domain.db
                backup=yes
    - name: Configure named forwarders.conf
      template: src=templates/named/forwarders.conf.j2
                dest=/var/named/forwarders.conf
                backup=yes
    - name: Configure named named.conf
      template: src=templates/named/named.conf.j2
                dest=/etc/named.conf
                backup=yes
    - name: FirewallD - permanent add-serivce named
      command: $firewall_cmd --permanent --add-service=dns
    - name: FirewallD - add-serivce named
      command: $firewall_cmd --add-service=dns

    # MongoDB Install and configure 
    #   This could be broken out into it's own playbook to allow for some
    #   fancy orchestration and replication set configuration but for now 
    #   we will keep this simple.
    - name: Install MongoDB
      action: yum pkg=mongodb state=latest
    - name: Install MongoDB Server
      action: yum pkg=mongodb-server state=latest
    - name: FirewallD - permanent add-port 27017/tcp
      command: $firewall_cmd --permanent --add-port=27017/tcp
    - name: FirewallD - add-port 27017/tcp
      command: $firewall_cmd --add-port=27017/tcp
    - name: MongoDB user/pw script template copy
      template: src=templates/mongodb/set_mongopw.sh.j2
                dest=/root/00-set_mongopw.sh
                owner=root group=root mode=0500
    - name: Run MongoDB user/pw script 
      action: raw /root/00-set_mongopw.sh
    - name: Clean up after MongoDB user/pw script
      file: path=/root/00-set_mongopw.sh state=absent


    ### Dev tools needed by some gem installs for native modules/extensions 
    - name: ruby-devel at latest version
      action: yum pkg=ruby-devel state=latest
    - name: mysql-devel at latest version
      action: yum pkg=mysql-devel state=latest
    - name: mongodb-devel at latest version
      action: yum pkg=mongodb-devel state=latest
    - name: gcc at latest version
      action: yum pkg=gcc state=latest
    - name: make at latest version
      action: yum pkg=make state=latest
    
    ### Big honking broker package list
    - name: openshift-origin-broker at latest version
      action: yum pkg=openshift-origin-broker state=latest
    - name: rubygem-openshift-origin-msg-broker-mcollective at latest version
      action: yum pkg=rubygem-openshift-origin-msg-broker-mcollective state=latest
    - name: rubygem-openshift-origin-dns-nsupdate at latest version
      action: yum pkg=rubygem-openshift-origin-dns-nsupdate state=latest
    - name: rubygem-openshift-origin-dns-bind at latest version
      action: yum pkg=rubygem-openshift-origin-dns-bind state=latest
    - name: rubygem-openshift-origin-controller at latest version
      action: yum pkg=rubygem-openshift-origin-controller state=latest
    - name: openshift-origin-broker-util at latest version
      action: yum pkg=openshift-origin-broker-util state=latest
    - name: rubygem-passenger at latest version
      action: yum pkg=rubygem-passenger state=latest
    - name: openssh at latest version
      action: yum pkg=openssh state=latest
    - name: mod_passenger at latest version
      action: yum pkg=mod_passenger state=latest
    - name: rubygem-rails at latest version
      action: yum pkg=rubygem-rails state=latest
    - name: rubygem-railties at latest version
      action: yum pkg=rubygem-railties state=latest
    - name: rubygem-actionpack at latest version
      action: yum pkg=rubygem-actionpack state=latest
    - name: rubygem-activemodel at latest version
      action: yum pkg=rubygem-activemodel state=latest
    - name: rubygem-activerecord at latest version
      action: yum pkg=rubygem-activerecord state=latest
    - name: rubygem-activeresource at latest version
      action: yum pkg=rubygem-activeresource state=latest
    - name: rubgem-arel at latest version
      action: yum pkg=rubygem-arel state=latest
    - name: rubygem-bigdecimal at latest version
      action: yum pkg=rubygem-bigdecimal state=latest
    - name: rubygem-bson at latest version
      action: yum pkg=rubygem-bson state=latest
    - name: rubygem-bson_ext at latest version
      action: yum pkg=rubygem-bson_ext state=latest
    - name: rubygem-builder at latest version
      action: yum pkg=rubygem-builder state=latest
    - name: rubygem-bundler at latest version
      action: yum pkg=rubygem-bundler state=latest
    - name: rubygem-cucumber at latest version
      action: yum pkg=rubygem-cucumber state=latest
    - name: rubygem-diff-lcs at latest version
      action: yum pkg=rubygem-diff-lcs state=latest
    - name: rubygem-dnsruby at latest version
      action: yum pkg=rubygem-dnsruby state=latest
    - name: rubygem-erubis at latest version
      action: yum pkg=rubygem-erubis state=latest
    - name: rubygem-gherkin at latest version
      action: yum pkg=rubygem-gherkin state=latest
    - name: rubygem-hike at latest version
      action: yum pkg=rubygem-hike state=latest
    - name: rubygem-i18n at latest version
      action: yum pkg=rubygem-i18n state=latest
    - name: rubygem-mail at latest version
      action: yum pkg=rubygem-mail state=latest
    - name: rubygem-metaclass at latest version
      action: yum pkg=rubygem-metaclass state=latest
    - name: rubygem-mime-types at latest version
      action: yum pkg=rubygem-mime-types state=latest
    - name: rubygem-minitest at latest version
      action: yum pkg=rubygem-minitest state=latest
    - name: rubgyem-mocha at latest version
      action: yum pkg=rubygem-mocha state=latest
    - name: rubygem-mongo at latest version
      action: yum pkg=rubygem-mongo state=latest
    - name: rubygem-multi_json at latest version
      action: yum pkg=rubygem-multi_json state=latest
    - name: rubygem-netrc at latest version
      action: yum pkg=rubygem-netrc state=latest
    - name: rubygem-open4 at latest version
      action: yum pkg=rubygem-open4 state=latest
    - name: rubygem-parseconfig at latest version
      action: yum pkg=rubygem-parseconfig state=latest
    - name: rubygem-rack at latest version
      action: yum pkg=rubygem-rack state=latest
    - name: rubygem-rack-cache at latest version
      action: yum pkg=rubygem-rack-cache state=latest
    - name: rubygem-rack-ssl at latest version
      action: yum pkg=rubygem-rack-ssl state=latest
    - name: rubygem-rack-test at latest version
      action: yum pkg=rubygem-rack-test state=latest
    - name: rubygem-rake at latest version
      action: yum pkg=rubygem-rake state=latest
    - name: rubygem-rdoc at latest version
      action: yum pkg=rubygem-rdoc state=latest
    - name: rubygem-regin at latest version
      action: yum pkg=rubygem-regin state=latest
    - name: rubygem-rest-client at latest version
      action: yum pkg=rubygem-rest-client state=latest
    - name: rubygem-simplecov at latest version
      action: yum pkg=rubygem-simplecov state=latest
    - name: rubgyem-simplecov-html at latest version
      action: yum pkg=rubygem-simplecov state=latest
    - name: rubygem-sprockets at latest version
      action: yum pkg=rubygem-sprockets state=latest
    - name: rubgyem-state_machine at latest version
      action: yum pkg=rubygem-state_machine state=latest
    - name: rubygem-stomp at latest version
      action: yum pkg=rubygem-stomp state=latest
    - name: rubygem-systemu at latest version
      action: yum pkg=rubygem-systemu state=latest
    - name: rubygem-term-ansicolor at latest version
      action: yum pkg=rubygem-term-ansicolor state=latest
    - name: rubygem-thor at latest version
      action: yum pkg=rubygem-thor state=latest
    - name: rubygem-tilt at latest version
      action: yum pkg=rubygem-tilt state=latest
    - name: rubygem-treetop at latest version
      action: yum pkg=rubygem-treetop state=latest
    - name: rubygem-tzinfo at latest version
      action: yum pkg=rubygem-tzinfo state=latest
    - name: rubygem-xml-simple at latest version
      action: yum pkg=rubygem-xml-simple state=latest
    - name: rubygem-webmock at latest version
      action: yum pkg=rubygem-webmock state=latest
    - name: rubygem-fakefs at latest version
      action: yum pkg=rubygem-fakefs state=latest
    - name: mongoid gem installed
      command: $gem install mongoid 
    - name: origin gem installed 
      command: $gem install origin 
    - name: mysql gem installed
      command: $gem install mysql
