---
# This Playbook would deploy the entire OpenShift Origin environment

- hosts: all
  roles:
   - role: common
  tags:
    - common
    - nodes
    - brokers
    - support_nodes

- hosts: nodes
  roles:
    - role: oo-node
  tags:
    - nodes

- hosts: brokers
  roles:
    - role: oo-broker
    - role: oo-console
    - role: mcollective-client
  tags:
    - brokers

- hosts: support_nodes
  roles:
    - role: mongod
    - role: qpidd
      when: mq_provider == "qpid"
    - role: activemq
      when: mq_provider == "activemq"
    - role: named
  tags:
    - support_nodes

