---
### main.yml - common role for an OpenShift Origin deployment 
#
# Ansible playbook to deploy OpenShift Origin using nightly builds
#

# Setup repos
- name: Setup OpenShift Origin Nightly Repo
  template: src=openshift-origin-nightly.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-nightly.repo
- name: Setup OpenShift Origin Nightly Supplemental Repo
  template: src=openshift-origin-supplemental.repo.j2
            dest=/etc/yum.repos.d/openshift-origin-supplemental.repo

# Default firewalld configs
- name: Ensure Install - firewalld
  yum: pkg=firewalld state=installed
- name: Start and Enable firewalld daemon
  service: name=firewalld state=started enabled=yes
  async: 10
  poll: 2


# Ensure NTP installed and configured
- name: Ensure Install - ntpdate
  yum: pkg=ntpdate state=installed
- name: Ensure Install - ntp
  yum: pkg=ntp state=installed
- name: Stop ntp daemon for ntpdate sync
  service: name=ntpd state=stopped
- name: Synchronize Clock with ntpdate
  command: /usr/sbin/ntpdate clock.redhat.com
- name: Start and Enable ntp daemon
  service: name=ntpd state=started enabled=yes
